version: '3.7'
services:
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=ute
      - DOCKER_INFLUXDB_INIT_PASSWORD=supersecret
      - DOCKER_INFLUXDB_INIT_ORG=ute
      - DOCKER_INFLUXDB_INIT_BUCKET=ute
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token

volumes:
  influxdb_data:
